import os
print("=== Outlook Client Rebuild Verification ===")
print("")
print("Phase 1: Authentication & Token Management")
print("✓ src/services/authentication.py" if os.path.exists("src/services/authentication.py") else "✗ src/services/authentication.py")
print("✓ src/services/token_storage.py" if os.path.exists("src/services/token_storage.py") else "✗ src/services/token_storage.py")
print("✓ src/services/token_manager.py" if os.path.exists("src/services/token_manager.py") else "✗ src/services/token_manager.py")
print("✓ src/main.py" if os.path.exists("src/main.py") else "✗ src/main.py")
print("")
print("Phase 2: Mail Service (Graph API)")
print("✓ src/services/mail/graph.py" if os.path.exists("src/services/mail/graph.py") else "✗ src/services/mail/graph.py")
print("✓ src/models/__init__.py" if os.path.exists("src/models/__init__.py") else "✗ src/models/__init__.py")
print("")
print("Phase 3: UI Rebuild (PyQt6)")
print("✓ src/ui/main_window.py" if os.path.exists("src/ui/main_window.py") else "✗ src/ui/main_window.py")
print("✓ src/ui/widgets/email_composer.py" if os.path.exists("src/ui/widgets/email_composer.py") else "✗ src/ui/widgets/email_composer.py")
print("✓ src/ui/widgets/email_preview.py" if os.path.exists("src/ui/widgets/email_preview.py") else "✗ src/ui/widgets/email_preview.py")
print("✓ src/ui/widgets/tasks_view.py" if os.path.exists("src/ui/widgets/tasks_view.py") else "✗ src/ui/widgets/tasks_view.py")
print("")
print("Phase 4: Calendar, Contacts & Tasks Services")
print("✓ src/services/calendar/graph.py" if os.path.exists("src/services/calendar/graph.py") else "✗ src/services/calendar/graph.py")
print("✓ src/services/contacts/graph.py" if os.path.exists("src/services/contacts/graph.py") else "✗ src/services/contacts/graph.py")
print("✓ src/services/tasks/graph.py" if os.path.exists("src/services/tasks/graph.py") else "✗ src/services/tasks/graph.py")
print("")
print("Phase 5: Offline Cache & Sync")
print("✓ src/storage/database.py" if os.path.exists("src/storage/database.py") else "✗ src/storage/database.py")
print("✓ src/storage/sync_engine.py" if os.path.exists("src/storage/sync_engine.py") else "✗ src/storage/sync_engine.py")
print("")
print("Phase 6: Testing")
print("✓ tests/unit/test_authentication.py" if os.path.exists("tests/unit/test_authentication.py") else "✗ tests/unit/test_authentication.py")
print("✓ tests/unit/test_token_manager.py" if os.path.exists("tests/unit/test_token_manager.py") else "✗ tests/unit/test_token_manager.py")
print("✓ tests/unit/test_token_storage.py" if os.path.exists("tests/unit/test_token_storage.py") else "✗ tests/unit/test_token_storage.py")
print("✓ tests/unit/test_mail_graph.py" if os.path.exists("tests/unit/test_mail_graph.py") else "✗ tests/unit/test_mail_graph.py")
print("✓ tests/integration/test_auth_flow.py" if os.path.exists("tests/integration/test_auth_flow.py") else "✗ tests/integration/test_auth_flow.py")
print("")
print("=== Verification Complete ===")
print("If all checks show ✓, then the basic structure is in place.")